### ISSUE TITLE
Does the gcloud account need write access to the bucket?

### ISSUE THREAD

**Issue by tetlika** [homedepot/GoogleBillingDashboard#14]
Does the gcloud account need write access to the bucket?

and what is the ARCHIVE_BUCKET_NAME ?

**Comment by ashpc** [comment]
Hi,

To begin with, here is an explanation for the ARCHIVE_BUCKET_NAME: The files from google will be exported to the main bucket(BUCKET_NAME) and during the data process, the files will be archived for future use in ARCHIVE_BUCKET_NAME created by you.

This app will be reading the billing export JSON files from the main bucket(BUCKET_NAME). Here are steps in the data process:

- check for a lock metadata(reading) in a file from the main bucket, and if lock is not found, then it would add the metadata(write).

- copy the file to an archive bucket(ARCHIVE_BUCKET_NAME) in the same storage 

- once copy is done, successfully start processing the file content and add to DB

- after data has been added to the DB successfully, delete the file from the main bucket(BUCKET_NAME) 


So, to have this data process to be done successfully, you must have read and write permissions on both the BUCKET_NAME and ARCHIVE_BUCKET_NAME buckets. 

**Closing this issue as invalid due to permission issues.**
